name: '✨ feature'
description: '기능 추가 이슈 템플릿'
title : 'Feat/이슈를 작성해주세요'
labels : [✨ Feature]
assignees : ['채민']

body:
  - type: markdown
    attributes:
      value: |
        ### 📝 제목 작성 규칙
        제목은 반드시 `Feat/ ~` 형식으로 작성해주세요.  
        예: `Feat/A 기능 구현`

  - type: input
    id: description
    attributes:
      label: '이슈 내용 (Description)'
      description: '이슈 대해 간략히 요약해주세요'
    validations:
      required: true

  - type : textarea
    id : details
    attributes:
      label : '상세 내용 (Details)'
      description: '이슈 대해 자세히 설명해주세요'
      value: |
        - About Details

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트 (Tasks)'
      description: '해당 이슈 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Tasks1
        - [ ] Tasks2
